
# BEGIN_KITTY_THEME
# Kanagawa
include Kanagawa_dragon.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family="JetBrains Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

font_size 15.0
modify_font underline_position 2
background_opacity 1.0
background_blur 20
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_align left 
cursor_blink_interval 0.7 ease-in-out
cursor_trail 1
cursor_trail_decay 0.1 0.4
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{index}:{title}"
window_border_width 0.5pt
draw_window_borders_for_single_window no

hide_window_decorations no
# macos_titlebar_color background
hide_window_decorations titlebar-only
window_margin_width 5
adjust_line_height 110%





map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9
map cmd+] next_tab
map cmd+[ previous_tab
