--require'shade'.setup({
--  overlay_opacity = 60,
--  opacity_step = 1,
--  keys = {
--    brightness_up    = '<space><Up>',
--    brightness_down  = '<space><Down>',
--    toggle           = '<space>s',
--  }
--})
